export const domesticOrder = {
  orderId: 28105410,
  orderNumber: "3501901814",
  orderKey: "3501901814",
  orderDate: "2024-11-27T17:44:46.0000000",
  createDate: "2024-11-27T18:09:43.8100000",
  modifyDate: "2024-11-27T18:09:44.5200000",
  paymentDate: "2024-11-27T17:44:52.0000000",
  shipByDate: "2024-12-18T23:59:00.0000000",
  orderStatus: "awaiting_shipment",
  customerId: 11300498,
  customerUsername: "1011815220",
  customerEmail: "joc607@mail.harvard.edu",
  billTo: {
    name: "Jordan Evans",
    company: null,
    street1: "46 Fiske Rd",
    street2: "",
    street3: null,
    city: "Wellesley",
    state: "MA",
    postalCode: "02481",
    country: "US",
    phone: null,
    residential: null,
    addressVerified: null,
  },
  shipTo: {
    name: "Jordan Evans",
    company: null,
    street1: "46 FISKE RD",
    street2: "",
    street3: null,
    city: "WELLESLEY",
    state: "MA",
    postalCode: "02481-3426",
    country: "US",
    phone: null,
    residential: true,
    addressVerified: "Address validated successfully",
  },
  items: [
    {
      orderItemId: 1402187604349,
      lineItemKey: "4363384403",
      sku: '19343365769_30"x6Feet_8E791',
      name: "Geometric Wood Art - Spectrum",
      imageUrl:
        "https://i.etsystatic.com/25023581/r/il/be3d0e/5676970772/il_fullxfull.5676970772_7hde.jpg",
      weight: {
        value: 640,
        units: "ounces",
        WeightUnits: 1,
      },
      quantity: 1,
      unitPrice: 920,
      taxAmount: 0,
      shippingAmount: 0,
      warehouseLocation: null,
      options: [
        {
          name: "Size",
          value: '30" x 6 Feet',
        },
      ],
      productId: 3825987,
      fulfillmentSku: null,
      adjustment: false,
      upc: null,
      createDate: "2024-11-27T18:09:43.733",
      modifyDate: "2024-11-27T18:09:43.733",
    },
    {
      orderItemId: 1402187604350,
      lineItemKey: "Discount",
      sku: "",
      name: "Discount",
      imageUrl: null,
      weight: null,
      quantity: 1,
      unitPrice: -92,
      taxAmount: null,
      shippingAmount: null,
      warehouseLocation: null,
      options: [],
      productId: null,
      fulfillmentSku: null,
      adjustment: true,
      upc: null,
      createDate: "2024-11-27T18:09:43.733",
      modifyDate: "2024-11-27T18:09:43.733",
    },
  ],
  orderTotal: 879.75,
  amountPaid: 879.75,
  taxAmount: 51.75,
  shippingAmount: 0,
  customerNotes: null,
  internalNotes: null,
  gift: false,
  giftMessage: null,
  paymentMethod: "cc",
  requestedShippingService: "Standard Shipping",
  carrierCode: null,
  serviceCode: null,
  packageCode: null,
  confirmation: "none",
  shipDate: null,
  holdUntilDate: null,
  weight: {
    value: 640,
    units: "ounces",
    WeightUnits: 1,
  },
  dimensions: {
    units: "inches",
    length: 10,
    width: 10,
    height: 10,
  },
  insuranceOptions: {
    provider: null,
    insureShipment: false,
    insuredValue: 0,
  },
  internationalOptions: {
    contents: null,
    customsItems: null,
    nonDelivery: null,
  },
  advancedOptions: {
    warehouseId: null,
    nonMachinable: false,
    saturdayDelivery: false,
    containsAlcohol: false,
    mergedOrSplit: false,
    mergedIds: [],
    parentId: null,
    storeId: 673940,
    customField1: "",
    customField2: "",
    customField3: "",
    source: "etsy",
    billToParty: null,
    billToAccount: null,
    billToPostalCode: null,
    billToCountryCode: null,
    billToMyOtherAccount: null,
  },
  tagIds: null,
  userId: null,
  externallyFulfilled: false,
  externallyFulfilledBy: null,
  externallyFulfilledById: null,
  externallyFulfilledByName: null,
  labelMessages: null,
};

// Sample 2: International order with customs information
const internationalOrder: ShipStationOrder = {
  orderId: 789012,
  orderNumber: "INT-001",
  orderKey: "INT-001-B",
  orderDate: "2023-05-16T09:15:00.000Z",
  createDate: "2023-05-16T09:15:00.000Z",
  modifyDate: "2023-05-16T09:20:00.000Z",
  paymentDate: "2023-05-16T09:17:00.000Z",
  shipByDate: "2023-05-18T23:59:59.000Z",
  orderStatus: "awaiting_shipment",
  customerId: 45678,
  customerUsername: "emilybrown",
  customerEmail: "emily.brown@example.com",
  billTo: {
    name: "Emily Brown",
    company: "Brown Enterprises",
    street1: "789 Billing Road",
    street2: "",
    street3: "",
    city: "London",
    state: "",
    postalCode: "SW1A 1AA",
    country: "GB",
    phone: "+44 20 1234 5678",
    residential: false,
  },
  shipTo: {
    name: "Emily Brown",
    company: "Brown Enterprises",
    street1: "101 Shipping Street",
    street2: "Floor 3",
    street3: "",
    city: "Paris",
    state: "",
    postalCode: "75001",
    country: "FR",
    phone: "+33 1 23 45 67 89",
    residential: false,
  },
  items: [
    {
      orderItemId: 3,
      lineItemKey: "SKU-003",
      sku: "BOOK-001",
      name: "International Business Guide",
      imageUrl: "https://example.com/images/business-book.jpg",
      weight: {
        value: 2,
        units: "pounds",
      },
      quantity: 1,
      unitPrice: 49.99,
      taxAmount: 10,
      shippingAmount: 15,
      warehouseLocation: "Aisle 5, Shelf 1",
      options: [],
      productId: 102,
      fulfillmentSku: "BOOK-001-ENG",
      adjustment: false,
      upc: "123456789014",
      createDate: "2023-05-16T09:15:00.000Z",
      modifyDate: "2023-05-16T09:15:00.000Z",
    },
  ],
  orderTotal: 74.99,
  amountPaid: 74.99,
  taxAmount: 10,
  shippingAmount: 15,
  customerNotes: "Please deliver during business hours",
  internalNotes: "High-value item, signature required",
  gift: false,
  giftMessage: "",
  paymentMethod: "paypal",
  requestedShippingService: "DHL Express",
  carrierCode: "dhl_express",
  serviceCode: "express_worldwide",
  packageCode: "package",
  confirmation: "signature",
  shipDate: "2023-05-17T11:00:00.000Z",
  holdUntilDate: "2023-05-17T09:00:00.000Z",
  weight: {
    value: 2,
    units: "pounds",
  },
  dimensions: {
    length: 11,
    width: 8.5,
    height: 2,
    units: "inches",
  },
  insuranceOptions: {
    provider: "carrier",
    insureShipment: true,
    insuredValue: 74.99,
  },
  internationalOptions: {
    contents: "merchandise",
    customsItems: [
      {
        customsItemId: 1,
        description: "Business Book",
        quantity: 1,
        value: 49.99,
        harmonizedTariffCode: "4901.99.0000",
        countryOfOrigin: "US",
      },
    ],
    nonDelivery: "return_to_sender",
  },
  advancedOptions: {
    warehouseId: 67890,
    nonMachinable: false,
    saturdayDelivery: false,
    containsAlcohol: false,
    storeId: 12345,
    customField1: "International Customer",
    customField2: "Promo: GLOBAL2023",
    customField3: "",
    source: "Manual",
    mergedOrSplit: false,
    mergedIds: [],
    parentId: null,
    billToParty: "recipient",
    billToAccount: "",
    billToPostalCode: "75001",
    billToCountryCode: "FR",
  },
  tagIds: [2, 5],
  userId: "user_456",
  externallyFulfilled: false,
  externallyFulfilledBy: "",
};
